# $NetBSD: Makefile.common,v 1.115 2024/12/09 08:33:51 adam Exp $
#
# used by databases/sqlite3/Makefile
# used by databases/sqlite3-docs/Makefile
# used by databases/sqlite3-tcl/Makefile
# used by devel/lemon/Makefile

SQLITE3_DISTVERSION=	3530400
SQLITE3_VERSION=	3.53.4

MASTER_SITES=	http://www.sqlite.org/2026/
MASTER_SITES+=	http://www.hwaci.com/sw/sqlite/2026/

HOMEPAGE?=	http://www.sqlite.org/
LICENSE=	public-domain
